/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTwinRouteImport } from './routes/_authenticated/twin'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesPeerRouteImport } from './routes/_authenticated/messages.$peer'
import { Route as AuthLinkedinCompleteRouteImport } from './routes/auth.linkedin.complete'
import { Route as ApiPublicAuthLinkedinCallbackRouteImport } from './routes/api/public/auth/linkedin/callback'
import { Route as ApiPublicAuthLinkedinStartRouteImport } from './routes/api/public/auth/linkedin/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwinRoute = AuthenticatedTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedMessagesPeerRoute =
  AuthenticatedMessagesPeerRouteImport.update({
    id: '/$peer',
    path: '/$peer',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthLinkedinCompleteRoute = AuthLinkedinCompleteRouteImport.update({
  id: '/linkedin/complete',
  path: '/linkedin/complete',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicAuthLinkedinCallbackRoute =
  ApiPublicAuthLinkedinCallbackRouteImport.update({
    id: '/api/public/auth/linkedin/callback',
    path: '/api/public/auth/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLinkedinStartRoute =
  ApiPublicAuthLinkedinStartRouteImport.update({
    id: '/api/public/auth/linkedin/start',
    path: '/api/public/auth/linkedin/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/twin': typeof AuthenticatedTwinRoute
  '/messages/$peer': typeof AuthenticatedMessagesPeerRoute
  '/auth/linkedin/complete': typeof AuthLinkedinCompleteRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/twin': typeof AuthenticatedTwinRoute
  '/messages/$peer': typeof AuthenticatedMessagesPeerRoute
  '/auth/linkedin/complete': typeof AuthLinkedinCompleteRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/twin': typeof AuthenticatedTwinRoute
  '/_authenticated/messages/$peer': typeof AuthenticatedMessagesPeerRoute
  '/auth/linkedin/complete': typeof AuthLinkedinCompleteRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/messages'
    | '/network'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/twin'
    | '/messages/$peer'
    | '/auth/linkedin/complete'
    | '/messages/'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/network'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/twin'
    | '/messages/$peer'
    | '/auth/linkedin/complete'
    | '/messages'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/network'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/twin'
    | '/_authenticated/messages/$peer'
    | '/auth/linkedin/complete'
    | '/_authenticated/messages/'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiPublicAuthLinkedinCallbackRoute: typeof ApiPublicAuthLinkedinCallbackRoute
  ApiPublicAuthLinkedinStartRoute: typeof ApiPublicAuthLinkedinStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twin': {
      id: '/_authenticated/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof AuthenticatedTwinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/messages/$peer': {
      id: '/_authenticated/messages/$peer'
      path: '/$peer'
      fullPath: '/messages/$peer'
      preLoaderRoute: typeof AuthenticatedMessagesPeerRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/auth/linkedin/complete': {
      id: '/auth/linkedin/complete'
      path: '/linkedin/complete'
      fullPath: '/auth/linkedin/complete'
      preLoaderRoute: typeof AuthLinkedinCompleteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/auth/linkedin/callback': {
      id: '/api/public/auth/linkedin/callback'
      path: '/api/public/auth/linkedin/callback'
      fullPath: '/api/public/auth/linkedin/callback'
      preLoaderRoute: typeof ApiPublicAuthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/linkedin/start': {
      id: '/api/public/auth/linkedin/start'
      path: '/api/public/auth/linkedin/start'
      fullPath: '/api/public/auth/linkedin/start'
      preLoaderRoute: typeof ApiPublicAuthLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesPeerRoute: typeof AuthenticatedMessagesPeerRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesPeerRoute: AuthenticatedMessagesPeerRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTwinRoute: typeof AuthenticatedTwinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTwinRoute: AuthenticatedTwinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthLinkedinCompleteRoute: typeof AuthLinkedinCompleteRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLinkedinCompleteRoute: AuthLinkedinCompleteRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiPublicAuthLinkedinCallbackRoute: ApiPublicAuthLinkedinCallbackRoute,
  ApiPublicAuthLinkedinStartRoute: ApiPublicAuthLinkedinStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
